name: spotify
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.25.4
  cupertino_icons: ^1.0.6
  firebase_auth: ^4.17.5
  flutter_svg: ^2.0.10+1
  flutter_bloc: ^8.1.6
  bloc: ^8.1.4
  get_it: ^7.7.0
  shared_preferences: ^2.3.1
  provider: ^6.1.2
  flutter_icon_snackbar: ^1.1.7
  cloud_firestore: ^4.17.5
  cached_network_image: ^3.4.0
  shimmer: ^3.0.0
  just_audio: ^0.9.39
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0


flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  fonts:
    - family: Satoshi
      fonts:
        - asset: assets/fonts/Satoshi-Black.otf
          weight: 900
        - asset: assets/fonts/Satoshi-Bold.otf
          weight: 600
        - asset: assets/fonts/Satoshi-Light.otf
          weight: 500
        - asset: assets/fonts/Satoshi-Medium.otf
          weight: 400
        - asset: assets/fonts/Satoshi-Regular.otf
          weight: 300

  assets:
    - assets/images/
    - assets/fonts/
    - lib/features/home/
    - lib/features/home/domain/
    - lib/features/home/presentation/

