// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCT8J9fEsTqk14GDHHsbqPb4gfR-IPjGEg',
    appId: '1:977021658199:web:683b0849e403cb5823af12',
    messagingSenderId: '977021658199',
    projectId: 'spotifyzzd',
    authDomain: 'spotifyzzd.firebaseapp.com',
    storageBucket: 'spotifyzzd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBBRxsKQmC9DjU50iXVAAKAOqsmCRUG_EY',
    appId: '1:977021658199:ios:4c422c299e61e3e423af12',
    messagingSenderId: '977021658199',
    projectId: 'spotifyzzd',
    storageBucket: 'spotifyzzd.appspot.com',
    iosBundleId: 'com.example.spotify',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCT8J9fEsTqk14GDHHsbqPb4gfR-IPjGEg',
    appId: '1:977021658199:web:4e4a1083e8018dc723af12',
    messagingSenderId: '977021658199',
    projectId: 'spotifyzzd',
    authDomain: 'spotifyzzd.firebaseapp.com',
    storageBucket: 'spotifyzzd.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAWjia1_NuV3wPLWgdbuGODTd818CiDeR8',
    appId: '1:977021658199:android:5f2796837fc960bf23af12',
    messagingSenderId: '977021658199',
    projectId: 'spotifyzzd',
    storageBucket: 'spotifyzzd.appspot.com',
  );

}